---
- name: Configure server-settings
  template:
    src: server-settings.json.j2
    dest: "{{ factorio_working_dir }}/data/server-settings.json"
    owner: factorio
    group: factorio
    mode: 0644
  notify:
    - restart factorio

- name: Configure map-gen-settings
  template:
    src: map-gen-settings.json.j2
    dest: "{{ factorio_working_dir }}/data/map-gen-settings.json"
    owner: factorio
    group: factorio
    mode: 0644

- name: Install rsyslog factorio conf
  template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.d/51-factorio.conf
  notify:
    - restart rsyslog

- name: Create systemd for factorio service
  template:
    src: factorio-systemd.service.j2
    dest: /etc/systemd/system/factorio.service
  notify:
    - restart factorio

- name: Create sync lock script
  template:
    src: s3_sync_lock.sh.j2
    dest: "{{ factorio_home_dir }}/s3_sync_lock.sh"
    owner: factorio
    group: factorio
    mode: 0755

- name: Create sync watch script
  template:
    src: s3_sync_watch.sh.j2
    dest: "{{ factorio_home_dir }}/s3_sync_watch.sh"
    owner: factorio
    group: factorio
    mode: 0755

- name: Create systemd for sync service
  template:
    src: factorio-s3-sync-systemd.service.j2
    dest: /etc/systemd/system/factorio-s3-sync.service
  notify:
    - restart factorio_sync

- name: Check if game save exists
  stat:
    path: "{{ game_save_path }}"
  register: game_save_stat

- name: Create game save directory
  file:
    path: "{{ game_save_path | dirname }}"
    state: directory
    owner: factorio
    group: factorio
    mode: 0755
  when: game_save_stat.stat.exists != true

- name: Copy game save from local if configured to
  copy:
    src: "{{ local_game_save }}"
    dest: "{{ game_save_path }}"
    owner: factorio
    group: factorio
    mode: 0755
  when: local_game_save is defined

- name: Check if any game saves were copied to server
  stat:
    path: "{{ game_save_path }}"
  register: game_save_stat

- name: Copy game saves from S3 if save not found
  command: "aws s3 sync s3://{{ factorio_s3_bucket }}/{{ game_save_name }}/ {{ game_save_path | dirname }}"
  when: game_save_stat.stat.exists != true

- name: Check if any game saves were copied to server
  stat:
    path: "{{ game_save_path }}"
  register: game_save_stat

- name: Create initial game save if there is no local or S3 save available
  command: "{{ factorio_binary }} --create {{ game_save_path }} --map-gen-settings {{ factorio_working_dir}}/data/map-gen-settings.json"
  become: yes
  become_user: factorio
  when: game_save_stat.stat.exists != true
  notify:
    - restart factorio

