---
- name: Terminate factorio instance
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import factorio configuration overrides
      include_vars: factorio-config.yml

    - name: Terminate factorio instance
      ec2:
        region: "{{ region }}"
        exact_count: 0
        count_tag:
          Name: Factorio
        image: ami-a025aeb6
      register: ec2

