---
- name: Configure existing Factorio instance
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import factorio configuration overrides
      include_vars: factorio-config.yml

    - name: Find instance
      ec2:
        region: "{{ region }}"
        exact_count: 1
        count_tag:
          Name: Factorio
        image: ami-a025aeb6
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
      with_items: "{{ ec2.tagged_instances }}"

- name: Configure factorio instance(s)
  hosts: all
  become: True
  gather_facts: True
  remote_user: ubuntu
  roles:
    - factorio
